import { randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import spec from '../../packages/api-client/openapi.json';
import type { Project, Reference, Shot } from '@sceneproof/api-client';

test('approved film opens without upload, persists real references and frames, and resets only its working copy', async ({ page, request }) => {
  test.setTimeout(240000);
  expect(await (await request.get('/__test/provider')).json()).toEqual({ provider: 'deterministic-test-only' });
  const ordinary: Project = await (await request.post('/api/v1/projects', { data: { name: `PR7 ordinary ${Date.now()}`, rules: 'Preserve this ordinary project.' } })).json();
  const paidWrites: string[] = [];
  page.on('request', outgoing => { if (outgoing.method() === 'POST' && /\/(analyses|actions)(\?|$)/.test(outgoing.url())) paidWrites.push(outgoing.url()); });
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto('/');
  await expect(page.getByRole('link', { name: /create a project/i })).toBeVisible();
  const launch = page.getByRole('button', { name: 'Try the demo film' });
  const launched = page.waitForResponse(response => response.url().endsWith('/api/v1/demo') && response.request().method() === 'POST');
  await launch.focus(); await page.keyboard.press('Enter');
  await expect(page.getByText('Preparing your demo copy…')).toBeVisible();
  const launchResponse = await launched;
  expect(launchResponse.status()).toBe(200);
  const original: Project = await launchResponse.json();
  const validator = new Ajv2020({ strict: false, allErrors: true }); addFormats(validator); validator.addSchema(spec, 'sceneproof');
  const projectCheck = validator.compile({ $ref: 'sceneproof#/components/schemas/Project' });
  expect(projectCheck(original), JSON.stringify(projectCheck.errors)).toBe(true);
  expect(original.demo?.templateVersion).toBe('between-the-line-v1');
  await expect(page).toHaveURL(new RegExp(`/projects/${original.id}$`));
  await expect(page.getByText('Demo project', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start tour' })).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: original.name })).toBeFocused();
  await expect(page.locator('details.import-panel')).not.toHaveAttribute('open');
  await page.getByRole('button', { name: 'Skip', exact: true }).click();
  const bible = page.getByRole('complementary', { name: 'REFERENCE BIBLE' });
  const references: Reference[] = await (await request.get(`/api/v1/projects/${original.id}/references`)).json();
  const shots: Shot[] = await (await request.get(`/api/v1/projects/${original.id}/shots`)).json();
  expect(references).toHaveLength(5); expect(shots).toHaveLength(8);
  expect(shots.map(shot => shot.position)).toEqual([0, 1, 2, 3, 4, 5, 6, 7]);
  expect(shots.every(shot => shot.kind === 'VIDEO' && shot.status === 'READY' && shot.frames.length > 0)).toBe(true);
  await expect(bible.getByRole('img')).toHaveCount(5);
  for (const reference of references) {
    const thumbnail = bible.getByRole('img', { name: `Reference: ${reference.title}` });
    await expect(thumbnail).toHaveAttribute('src', reference.url);
    await expect(thumbnail).toHaveJSProperty('naturalWidth', reference.width);
  }
  await expect(page.getByText('No saved findings here.')).toBeVisible();
  const deterministicAnalysis = await request.post(`/api/v1/projects/${original.id}/analyses`, { data: { requestId: randomUUID() } });
  const deterministicRun = await deterministicAnalysis.json();
  expect(deterministicAnalysis.status(), JSON.stringify(deterministicRun)).toBe(200);
  expect(deterministicRun.status).toBe('SUCCEEDED');
  expect(deterministicRun.shotCount).toBe(8);
  expect(deterministicRun.frameCount).toBe(24);
  for (const width of [1280, 820, 390]) {
    await page.setViewportSize({ width, height: 900 });
    const shot = shots[7]!;
    const frame = page.getByRole('button', { name: `Select ${shot.name} frame 1`, exact: true });
    await frame.focus(); await page.keyboard.press('Enter');
    await expect(frame).toHaveAttribute('aria-pressed', 'true');
    const image = page.getByRole('img', { name: `Frame from ${shot.name}` });
    await expect(image).toHaveAttribute('src', shot.frames[0]!.url);
    await expect(image).toHaveJSProperty('naturalWidth', shot.frames[0]!.width);
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: `test-results/demo-${width}.png`, fullPage: true });
  }
  await page.getByLabel('Continuity rules', { exact: true }).fill('Creator changed these rules.');
  await page.getByRole('button', { name: 'Save rules' }).click();
  await expect(page.getByText('Rules saved.', { exact: true })).toBeVisible();
  await request.post(`/api/v1/projects/${original.id}/references/${references[0]!.id}/archive`);
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: 'Keep my changes' }).click();
  await expect(page.getByRole('button', { name: 'Reset demo', exact: true })).toBeFocused();
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
  const resetResponse = page.waitForResponse(response => response.url().endsWith(`/projects/${original.id}/demo/reset`));
  await dialog.getByRole('button', { name: 'Reset this copy' }).click();
  await expect(page.getByText('Restoring the authored demo…')).toBeVisible();
  const resetResult = await resetResponse; expect(resetResult.status()).toBe(200);
  const fresh: Project = await resetResult.json();
  expect(fresh.id).not.toBe(original.id); expect(fresh.demo?.instanceId).toBe(original.demo?.instanceId);
  await expect(page).toHaveURL(new RegExp(`/projects/${fresh.id}$`));
  await expect(page.getByLabel('Continuity rules', { exact: true })).toHaveValue(original.rules);
  await expect(bible.getByRole('img')).toHaveCount(5);
  await page.reload();
  await expect(page.getByLabel('Continuity rules', { exact: true })).toHaveValue(original.rules);
  await expect(page.getByText('No saved findings here.')).toBeVisible();
  const freshShots: Shot[] = await (await request.get(`/api/v1/projects/${fresh.id}/shots`)).json();
  expect(freshShots.map(shot => shot.name)).toEqual(shots.map(shot => shot.name));
  expect(freshShots[0]!.frames[0]!.id).not.toBe(shots[0]!.frames[0]!.id);
  expect((await (await request.get(`/api/v1/projects/${ordinary.id}`)).json()).rules).toBe(ordinary.rules);
  const replay: Project = await (await request.post(`/api/v1/projects/${original.id}/demo/reset`)).json(); expect(replay.id).toBe(fresh.id);
  await page.goto('/'); await page.getByRole('button', { name: 'Try the demo film' }).click();
  await expect(page).toHaveURL(new RegExp(`/projects/${fresh.id}$`));
  await page.goto(`/projects/${ordinary.id}`);
  await expect(page.getByRole('heading', { name: ordinary.name })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Reset demo' })).toHaveCount(0);
  expect(paidWrites).toEqual([]);
});

test('demo API rejects ordinary reset and invalid launch identities', async ({ request }) => {
  const original = await request.post('/api/v1/projects', { data: { name: `PR7 reset boundary ${randomUUID()}` } });
  const project: Project = await original.json();
  expect((await request.post(`/api/v1/projects/${project.id}/demo/reset`)).status()).toBe(409);
  expect((await request.post('/api/v1/demo', { data: { requestId: 'invalid' } })).status()).toBe(400);
});
