import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { expect, test } from '@playwright/test';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import spec from '../../packages/api-client/openapi.json';
import type { FilmIntelligence, FilmRun } from '@sceneproof/api-client';

test('film upload, durable stages, reload, evidence and creator confirmation use deterministic providers', async ({ page, request }) => {
  test.setTimeout(180000);
  expect(await (await request.get('/__test/provider')).json()).toEqual({ provider: 'deterministic-test-only' });
  const project = await (await request.post('/api/v1/projects', { data: { name: `PR8 film ${Date.now()}` } })).json();
  await page.addInitScript(() => localStorage.setItem('sceneproof.guided-tour.v1', 'skipped'));
  await page.goto(`/projects/${project.id}`);
  const panel = page.getByRole('region', { name: 'Film Intelligence' });
  await panel.locator('input[type=file]').setInputFiles('demo/between the lines - demo.mp4');
  await panel.getByRole('button', { name: 'Upload source film' }).click();
  await expect(panel.getByRole('button', { name: 'Understand film' })).toBeEnabled({ timeout: 30000 });
  let intelligence: FilmIntelligence = await (await request.get(`/api/v1/projects/${project.id}/film`)).json();
  expect(intelligence.runs).toHaveLength(0);
  await panel.getByRole('button', { name: 'Understand film' }).click();
  await expect(page.getByRole('dialog')).toContainText('at most one transcription and one Astra');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  expect((await (await request.get(`/api/v1/projects/${project.id}/film`)).json()).runs).toHaveLength(0);
  await panel.getByRole('button', { name: 'Understand film' }).click();
  const responsePromise = page.waitForResponse(response => response.url().endsWith('/film/runs') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Confirm & understand' }).click();
  const response = await responsePromise;
  expect(response.status()).toBe(202);
  const run: FilmRun = await response.json();
  await page.reload();
  await expect(panel.getByRole('button', { name: 'New understanding attempt' })).toBeDisabled();
  await expect(panel.getByText('Film Understanding complete', { exact: true })).toBeVisible({ timeout: 90000 });
  intelligence = await (await request.get(`/api/v1/projects/${project.id}/film`)).json();
  const validator = new Ajv2020({ strict: false, allErrors: true }); addFormats(validator); validator.addSchema(spec, 'sceneproof');
  const check = validator.compile({ $ref: 'sceneproof#/components/schemas/FilmIntelligence' });
  expect(check(intelligence), JSON.stringify(check.errors)).toBe(true);
  expect(intelligence.runs).toHaveLength(1);
  expect(intelligence.runs[0]!.id).toBe(run.id);
  expect(intelligence.runs[0]!.audioStatus).toBe('TRANSCRIBED');
  expect(intelligence.runs[0]!.stages.map(stage => stage.stage)).toEqual(['PREPARING_SOURCE', 'DETECTING_STRUCTURE', 'TRANSCRIBING_AUDIO', 'UNDERSTANDING_FILM', 'BUILDING_CANDIDATES', 'SUCCEEDED']);
  await expect(panel.getByText(/\d+%|AI is thinking/i)).toHaveCount(0);
  await panel.getByRole('button', { name: 'Accept anchor' }).first().click();
  const accepted = panel.locator('.film-candidate').first();
  await expect(accepted).toContainText('Creator-confirmed memory');
  await accepted.locator('summary').click();
  await expect(accepted.locator('img').first()).toBeVisible();
  await expect(accepted.locator('img').first()).toHaveJSProperty('naturalWidth', intelligence.segments[0]!.shot.frames[0]!.width);
  await expect(accepted).toContainText('Original deterministic test narration');
  await accepted.getByRole('button', { name: 'Add visual reference to Bible' }).click();
  await expect(accepted.getByRole('button', { name: 'Added to Reference Bible' })).toBeDisabled();
  await expect(page.getByRole('img', { name: 'Reference: Shape color' })).toBeVisible();
  await page.getByRole('button', { name: 'Inspect reference: Shape color' }).click();
  await expect(page.getByRole('dialog')).toContainText('Promoted from a creator-confirmed film anchor');
  await expect(page.getByRole('dialog').getByRole('link')).toHaveAttribute('href', `?filmRun=${run.id}`);
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await panel.getByRole('button', { name: 'Edit anchor' }).first().click();
  await page.getByLabel('Continuity expectation').fill('The creator expects a centered shape.');
  await page.getByRole('button', { name: 'Confirm edited anchor' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await panel.getByRole('button', { name: 'Reject anchor' }).click();
  await expect(panel.getByText('REJECTED', { exact: true })).toBeVisible();
  await page.reload();
  await expect(panel.getByText(/2 confirmed anchors/)).toBeVisible();
  for (const width of [1280, 820, 390]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await panel.scrollIntoViewIfNeeded();
    await page.screenshot({ path: `test-results/pr8-film-${width}.png`, fullPage: true });
  }
  const replay = await request.post(`/api/v1/projects/${project.id}/film/runs`, { data: { requestId: run.requestId, sourceFilmId: intelligence.source!.id, paidConsent: true } });
  expect((await replay.json()).id).toBe(run.id);
  expect((await (await request.get(`/api/v1/projects/${project.id}/film`)).json()).runs).toHaveLength(1);
});

test('film API requires consent and project ownership and refuses unsupported uploads', async ({ request }) => {
  expect(await (await request.get('/__test/provider')).json()).toEqual({ provider: 'deterministic-test-only' });
  const project = await (await request.post('/api/v1/projects', { data: { name: `PR8 boundary ${Date.now()}` } })).json();
  const sourceResponse = await request.post(`/api/v1/projects/${project.id}/film/source`, { multipart: { file: { name: 'original.mp4', mimeType: 'video/mp4', buffer: readFileSync('demo/runtime/shot-01.mp4') } } });
  expect(sourceResponse.status()).toBe(201);
  const source = await sourceResponse.json();
  const denied = await request.post(`/api/v1/projects/${project.id}/film/runs`, { data: { requestId: randomUUID(), sourceFilmId: source.id, paidConsent: false } });
  expect(denied.status()).toBe(400);
  const other = await (await request.post('/api/v1/projects', { data: { name: `PR8 other ${Date.now()}` } })).json();
  expect((await request.post(`/api/v1/projects/${other.id}/film/runs`, { data: { requestId: randomUUID(), sourceFilmId: source.id, paidConsent: true } })).status()).toBe(404);
  expect((await request.post(`/api/v1/projects/${other.id}/film/source`, { multipart: { file: { name: 'fake.mp4', mimeType: 'video/mp4', buffer: Buffer.from('not a video') } } })).status()).toBe(415);
  expect((await (await request.get(`/api/v1/projects/${project.id}/film`)).json()).runs).toHaveLength(0);
});
