import { randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import spec from '../../packages/api-client/openapi.json';
import type { Finding, Shot } from '@sceneproof/api-client';

test('project → persisted findings → evidence comparison → real clipboard, reload and tablet', async ({ page, request, context }) => {
  const marker = await request.get('/__test/provider');
  expect(marker.ok(), 'Start :apps:api:browserTestServer; never seed findings against a paid provider.').toBe(true);
  expect(await marker.json()).toEqual({ provider: 'deterministic-test-only' });
  const created = await request.post('/api/v1/projects', { data: { name: `Findings browser verification ${Date.now()}`, rules: 'The square stays red.' } });
  expect(created.status()).toBe(201);
  const project = await created.json();
  await page.goto(`/projects/${project.id}`);
  const shots: Shot[] = [];
  for (const [index, color] of ['#c9554d', '#527bc4', '#7094d6'].entries()) {
    const png = await page.evaluate(fill => { const canvas = document.createElement('canvas'); canvas.width = 640; canvas.height = 360; const drawing = canvas.getContext('2d')!; drawing.fillStyle = '#17201e'; drawing.fillRect(0, 0, 640, 360); drawing.fillStyle = fill; drawing.fillRect(220, 80, 200, 200); return canvas.toDataURL('image/png').split(',')[1]!; }, color);
    const imported = await request.post(`/api/v1/projects/${project.id}/shots`, { multipart: { file: { name: `square-${index + 1}.png`, mimeType: 'image/png', buffer: Buffer.from(png, 'base64') } } });
    expect(imported.status()).toBe(201);
    shots.push(await imported.json());
  }
  const analyzed = await request.post(`/api/v1/projects/${project.id}/analyses`, { data: { requestId: randomUUID() } });
  expect(analyzed.status()).toBe(200);
  const run = await analyzed.json();
  expect(run.status).toBe('SUCCEEDED');
  expect(run.usage).toBeNull();
  const results = await request.get(`/api/v1/projects/${project.id}/findings?analysisId=${run.id}`);
  const findings: Finding[] = await results.json();
  const finding = findings[0]!;
  const validator = new Ajv2020({ strict: false, allErrors: true });
  addFormats(validator); validator.addSchema(spec, 'sceneproof');
  const check = validator.compile({ $ref: 'sceneproof#/components/schemas/Finding' });
  expect(check(finding), JSON.stringify(check.errors)).toBe(true);
  const analysisWrites: string[] = [];
  page.on('request', outgoing => { if (outgoing.method() === 'POST' && outgoing.url().includes('/analyses')) analysisWrites.push(outgoing.url()); });
  await page.goto('/');
  await page.getByRole('link', { name: project.name }).click();
  const choice = page.getByRole('button', { name: /The square changes color/ });
  await expect(choice).toBeVisible();
  await choice.focus();
  await page.keyboard.press('Enter');
  await expect(choice).toHaveAttribute('aria-pressed', 'true');
  const viewer = page.getByRole('region', { name: 'Finding evidence' });
  const left = viewer.getByRole('img', { name: 'Evidence: square-1.png, frame 1' });
  const right = viewer.getByRole('img', { name: 'Evidence: square-2.png, frame 1' });
  await expect(left).toHaveAttribute('src', shots[0]!.frames[0]!.url);
  await expect(right).toHaveJSProperty('naturalWidth', 640);
  await expect(left).toHaveJSProperty('naturalWidth', 640);
  await expect(page.locator('.shot-affected')).toHaveCount(3);
  await expect(page.getByText('The square stays red.', { exact: true })).toHaveCount(2);
  await expect(page.getByText(finding.observedState, { exact: true })).toBeVisible();
  await expect(page.getByText(finding.explanation, { exact: true })).toBeVisible();
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  const copy = page.getByRole('button', { name: 'Copy correction' });
  await copy.focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('status').filter({ hasText: 'Correction copied.' })).toBeVisible();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(finding.suggestedCorrectionPrompt);
  await page.screenshot({ path: 'test-results/findings-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Shot 3 / frame 1' }).click();
  await expect(viewer.getByRole('img', { name: 'Evidence: square-3.png, frame 1' })).toHaveJSProperty('naturalWidth', 640);
  await page.reload();
  await expect(right).toHaveJSProperty('naturalWidth', 640);
  await expect(choice).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Refresh findings' }).click();
  await expect(choice).toBeVisible();
  await page.setViewportSize({ width: 820, height: 1180 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/findings-tablet.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.evaluate(() => { Object.defineProperty(navigator.clipboard, 'writeText', { configurable: true, value: () => Promise.reject(new Error('denied')) }); });
  await copy.click();
  await expect(page.getByRole('alert')).toContainText('Could not copy.');
  expect(analysisWrites).toEqual([]);
});
