import { expect, test } from '@playwright/test';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import spec from '../../packages/api-client/openapi.json';

test('import actual pixels, validate contract, reload and retain failed import history', async ({ page, request }) => {
  const created = await request.post('/api/v1/projects', { data: { name: `Media browser verification ${Date.now()}` } });
  const project = await created.json();
  await page.goto(`/projects/${project.id}`);
  const png = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 160; canvas.height = 90; const context = canvas.getContext('2d')!; context.fillStyle = '#ce5449'; context.fillRect(0, 0, 160, 90); return canvas.toDataURL('image/png').split(',')[1]; });
  await page.getByRole('region', { name: 'Media workspace' }).locator('input[type=file]').setInputFiles({ name: 'original-fixture.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') });
  await page.getByRole('button', { name: 'Import shot' }).click();
  const frame = page.getByRole('img', { name: 'Frame from original-fixture.png' });
  await expect(frame).toBeVisible();
  await expect(frame).toHaveJSProperty('naturalWidth', 160);
  await page.reload();
  await expect(frame).toBeVisible();
  await expect(page.getByText('Playhead · Still image')).toBeVisible();
  const listed = await request.get(`/api/v1/projects/${project.id}/shots`);
  const shots = await listed.json();
  const validator = new Ajv2020({ strict: false, allErrors: true });
  addFormats(validator); validator.addSchema(spec, 'sceneproof');
  const check = validator.compile({ $ref: 'sceneproof#/components/schemas/Shot' });
  expect(check(shots[0]), JSON.stringify(check.errors)).toBe(true);
  const foreign = await request.get(shots[0].frames[0].url.replace(project.id, '00000000-0000-0000-0000-000000000000'));
  expect(foreign.status()).toBe(404);
  await page.getByRole('region', { name: 'Media workspace' }).locator('input[type=file]').setInputFiles({ name: 'corrupt.png', mimeType: 'image/png', buffer: Buffer.from('not an image') });
  await page.getByRole('button', { name: 'Import shot' }).click();
  await expect(page.getByRole('alert')).toContainText('Import failed');
  await page.reload();
  await expect(page.getByText('Import failed · Unsupported or invalid file. Use JPEG, PNG or MP4/H.264.')).toBeVisible();
  await expect(frame).toHaveJSProperty('naturalWidth', 160);
  await page.screenshot({ path: 'test-results/media-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 820, height: 1180 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/media-tablet.png', fullPage: true });
});
