import { expect, test } from '@playwright/test';

test('create, persist, reload and reopen a continuity project', async ({ page }) => {
  const projectName = `Continuity review ${Date.now()}`;
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Your projects' })).toBeVisible();
  await page.screenshot({ path: 'test-results/landing-desktop.png', fullPage: true });
  await page.getByRole('link', { name: /create a project/i }).click();
  await page.getByLabel('Project name').fill(projectName);
  await page.getByLabel('Description').fill('Foundation browser verification');
  await page.getByLabel('Continuity rules').fill('The black blazer remains unchanged through the metro sequence.');
  await page.getByRole('button', { name: 'Create project' }).click();
  await expect(page).toHaveURL(/\/projects\/[0-9a-f-]{36}$/);
  await expect(page.getByRole('heading', { name: projectName })).toBeVisible();
  await page.reload();
  const privacyLink = page.getByRole('link', { name: 'Privacy details (opens a new tab)' });
  await expect(privacyLink).toBeVisible();
  await expect(privacyLink).toHaveAttribute('href', '/privacy');
  await expect(page.getByText(/Uploading alone does not start AI processing/).filter({ visible: true })).toHaveCount(1);
  await page.getByRole('tab', { name: 'Continuity Findings', exact: true }).click();
  await expect(privacyLink.filter({ visible: true })).toHaveCount(1);
  await page.getByRole('button', { name: 'Add visual reference' }).click();
  const uploadDialog = page.getByRole('dialog');
  await expect(uploadDialog.getByText(/Uploading alone does not start AI processing/)).toBeVisible();
  const popupPromise = page.waitForEvent('popup');
  await uploadDialog.getByRole('link', { name: 'Privacy details (opens a new tab)' }).click();
  const privacyPage = await popupPromise;
  await expect(privacyPage.getByRole('heading', { name: 'Privacy Policy', exact: true })).toBeVisible();
  await privacyPage.close();
  await expect(uploadDialog).toBeVisible();
  await uploadDialog.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.getByText('The black blazer remains unchanged through the metro sequence.')).toBeVisible();
  await expect(page.getByText('No continuity analysis has been run yet.')).toBeVisible();
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 820, height: 1180 });
  await expect(page.getByText('CONTINUITY FINDINGS', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/workspace-tablet.png', fullPage: true });
  await page.getByRole('link', { name: /all projects/i }).click();
  await expect(page.getByRole('link', { name: projectName, exact: true })).toBeVisible();
  await page.getByRole('link', { name: projectName, exact: true }).click();
  await expect(page.getByRole('heading', { name: projectName })).toBeVisible();
  expect(errors).toEqual([]);
});
