import { randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import spec from '../../packages/api-client/openapi.json';
import type { Finding, Reference } from '@sceneproof/api-client';

test('Reference Bible persists rules images and original finding citations through edit archive reload and targeted review', async ({ page, request }) => {
  const marker = await request.get('/__test/provider');
  expect(await marker.json()).toEqual({ provider: 'deterministic-test-only' });
  const created = await request.post('/api/v1/projects', { data: { name: `PR5 Reference Bible ${Date.now()}` } });
  expect(created.status()).toBe(201);
  const project = await created.json();
  const providerWrites: string[] = [];
  page.on('request', outgoing => { if (outgoing.method() === 'POST' && /\/(analyses|actions)(\?|$)/.test(new URL(outgoing.url()).pathname)) providerWrites.push(outgoing.url()); });
  await page.goto(`/projects/${project.id}`);
  await page.getByRole('tab', { name: 'Continuity Findings', exact: true }).click();
  await page.getByLabel('Continuity rules', { exact: true }).fill('The square stays red.');
  await page.getByRole('button', { name: 'Save rules' }).click();
  await expect(page.getByText('Rules saved.', { exact: true })).toBeVisible();
  const png = Buffer.from(await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 320; canvas.height = 180;
    const drawing = canvas.getContext('2d')!; drawing.fillStyle = '#17201e'; drawing.fillRect(0, 0, 320, 180);
    drawing.fillStyle = '#c9554d'; drawing.fillRect(100, 30, 120, 120);
    return canvas.toDataURL('image/png').split(',')[1]!;
  }), 'base64');
  const add = page.getByRole('button', { name: '+ Add visual reference' });
  await expect(add).toBeEnabled();
  await add.focus(); await page.keyboard.press('Enter');
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await dialog.locator('input[type=file]').setInputFiles({ name: 'original-reference.png', mimeType: 'image/png', buffer: png });
  await dialog.getByLabel('Reference title', { exact: true }).fill('Declared red prop');
  await dialog.getByLabel('Creator guidance', { exact: true }).fill('Keep this red square consistent.');
  const uploaded = page.waitForResponse(response => response.url().endsWith(`/projects/${project.id}/references`) && response.request().method() === 'POST');
  await dialog.getByRole('button', { name: 'Save reference' }).click();
  const response = await uploaded;
  expect(response.status()).toBe(201);
  const reference: Reference = await response.json();
  const validator = new Ajv2020({ strict: false, allErrors: true }); addFormats(validator); validator.addSchema(spec, 'sceneproof');
  const referenceCheck = validator.compile({ $ref: 'sceneproof#/components/schemas/Reference' });
  expect(referenceCheck(reference), JSON.stringify(referenceCheck.errors)).toBe(true);
  const bible = page.getByRole('complementary', { name: 'REFERENCE BIBLE' });
  await expect(bible.getByRole('img', { name: 'Reference: Declared red prop' })).toHaveJSProperty('naturalWidth', 320);
  await expect(dialog).not.toBeVisible();
  await page.reload();
  await page.getByRole('tab', { name: 'Continuity Findings', exact: true }).click();
  await expect(page.getByLabel('Continuity rules', { exact: true })).toHaveValue('The square stays red.');
  await expect(bible.getByRole('img')).toHaveAttribute('src', reference.url);
  expect(providerWrites).toEqual([]);
  for (const name of ['first.png', 'second.png']) {
    const imported = await request.post(`/api/v1/projects/${project.id}/shots`, { multipart: { file: { name, mimeType: 'image/png', buffer: png } } });
    expect(imported.status()).toBe(201);
  }
  const requestId = randomUUID();
  const analyzed = await request.post(`/api/v1/projects/${project.id}/analyses`, { data: { requestId } });
  expect(analyzed.status()).toBe(200);
  const run = await analyzed.json();
  expect(run.status).toBe('SUCCEEDED');
  const findings: Finding[] = await (await request.get(`/api/v1/projects/${project.id}/findings?analysisId=${run.id}`)).json();
  const finding = findings[0]!;
  expect(finding.relevantReferenceIds).toEqual([reference.id]);
  const findingCheck = validator.compile({ $ref: 'sceneproof#/components/schemas/Finding' });
  expect(findingCheck(finding), JSON.stringify(findingCheck.errors)).toBe(true);
  await page.goto(`/projects/${project.id}?analysisId=${run.id}&finding=${finding.id}`);
  const evidence = page.getByRole('region', { name: 'Reference evidence' });
  await expect(evidence.getByRole('img')).toHaveJSProperty('naturalWidth', 320);
  await expect(page.getByRole('region', { name: 'Finding evidence' }).getByRole('img')).toHaveCount(2);
  await bible.getByRole('button', { name: 'Inspect reference: Declared red prop' }).click();
  await dialog.getByLabel('Reference title', { exact: true }).fill('Updated Bible title');
  await dialog.getByLabel('Creator guidance', { exact: true }).fill('New guidance for later analysis.');
  await dialog.getByRole('button', { name: 'Save reference' }).click();
  await expect(bible.getByRole('button', { name: 'Inspect reference: Updated Bible title' })).toBeVisible();
  await expect(evidence.getByText('Keep this red square consistent.', { exact: true })).toBeVisible();
  await bible.getByRole('button', { name: 'Inspect reference: Updated Bible title' }).click();
  await dialog.getByRole('button', { name: 'Archive reference', exact: true }).click();
  await dialog.getByRole('button', { name: 'Confirm archive' }).click();
  await expect(bible.getByText('No visual references yet.')).toBeVisible();
  await expect(evidence.getByText(/Archived from the current Bible/)).toBeVisible();
  await page.reload();
  await expect(evidence.getByRole('img')).toHaveAttribute('src', reference.url);
  await expect(evidence.getByText('Declared red prop', { exact: true })).toBeVisible();
  expect(providerWrites).toEqual([]);
  await page.screenshot({ path: 'test-results/references-desktop.png', fullPage: true });
  for (const width of [820, 390]) {
    await page.setViewportSize({ width, height: 1000 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    if (width === 820) await page.screenshot({ path: 'test-results/references-tablet.png', fullPage: true });
  }
  const action = await request.post(`/api/v1/projects/${project.id}/findings/${finding.id}/actions`, { data: { requestId: randomUUID(), type: 'INTENTIONAL_CHANGE', explanation: 'The issue remains despite repainting.', scope: 'Between the affected shots.', affectedShotIds: finding.affectedShotIds } });
  expect(action.status()).toBe(200);
  expect((await action.json()).result.outcome).toBe('ISSUE_REMAINS');
  await page.reload();
  await expect(evidence.getByRole('img')).toHaveJSProperty('naturalWidth', 320);
  const replay = await request.post(`/api/v1/projects/${project.id}/analyses`, { data: { requestId } });
  expect(await replay.json()).toEqual(run);
});

test('reference editing failures remain isolated and modal restores keyboard focus', async ({ page, request }) => {
  const project = await (await request.post('/api/v1/projects', { data: { name: `PR5 reference failure ${Date.now()}` } })).json();
  await page.goto(`/projects/${project.id}`);
  await page.getByRole('tab', { name: 'Continuity Findings', exact: true }).click();
  await page.route(`**/projects/${project.id}/rules`, route => route.fulfill({ status: 503, contentType: 'application/problem+json', body: JSON.stringify({ title: 'Unavailable', status: 503, detail: 'Rules storage unavailable.' }) }));
  await page.getByLabel('Continuity rules', { exact: true }).fill('Unsaved draft');
  await page.getByRole('button', { name: 'Save rules' }).click();
  await expect(page.getByRole('alert')).toContainText('Rules storage unavailable.');
  await expect(page.getByLabel('Continuity rules', { exact: true })).toHaveValue('Unsaved draft');
  const add = page.getByRole('button', { name: '+ Add visual reference' });
  await expect(add).toBeEnabled();
  await add.focus(); await page.keyboard.press('Enter');
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await dialog.getByLabel('Reference title', { exact: true }).fill('Corrupt fixture');
  await dialog.locator('input[type=file]').setInputFiles({ name: 'bad.png', mimeType: 'image/png', buffer: Buffer.from('fake PNG') });
  await dialog.getByRole('button', { name: 'Save reference' }).click();
  await expect(dialog.getByRole('alert')).toContainText('Use a valid JPEG or PNG');
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(add).toBeFocused();
  await expect(page.getByRole('heading', { name: 'No continuity analysis has been run yet.' })).toBeVisible();
});
