import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';
import type { FilmIntelligence } from '@sceneproof/api-client';

test('PR9 progress, evidence, keyboard range and deletion across desktop tablet and narrow layouts', async ({ page, request }) => {
  test.setTimeout(180000);
  expect(await (await request.get('/__test/provider')).json()).toEqual({ provider: 'deterministic-test-only' });
  const project = await (await request.post('/api/v1/projects', { data: { name: `PR9 inspection ${Date.now()}` } })).json();
  const sourceResponse = await request.post(`/api/v1/projects/${project.id}/film/source`, { multipart: { file: { name: 'Analysis source.mp4', mimeType: 'video/mp4', buffer: readFileSync('demo/runtime/analysis-source.mp4') } } });
  expect(sourceResponse.status()).toBe(201);
  const source = await sourceResponse.json();
  await request.post(`/api/v1/projects/${project.id}/film/runs`, { data: { requestId: randomUUID(), sourceFilmId: source.id, paidConsent: true } });
  const active: FilmIntelligence = await (await request.get(`/api/v1/projects/${project.id}/film`)).json();
  expect(active.runs[0]!.completedAt).toBeNull();
  await page.addInitScript(() => localStorage.setItem('sceneproof.guided-tour.v1', 'skipped'));
  await page.route(`**/api/v1/projects/${project.id}/film`, route => route.fulfill({ json: active }));
  await page.goto(`/projects/${project.id}`);
  const panel = page.getByRole('region', { name: 'Film Intelligence' });
  const filmTab = page.getByRole('tab', { name: 'Film Intelligence', exact: true });
  const findingsTab = page.getByRole('tab', { name: 'Continuity Findings', exact: true });
  await expect(filmTab).toHaveAttribute('aria-selected', 'true');
  const backgroundPoll = page.waitForRequest(value => value.method() === 'GET' && value.url().endsWith(`/projects/${project.id}/film`));
  await filmTab.focus(); await page.keyboard.press('ArrowRight');
  await expect(findingsTab).toBeFocused();
  await expect(page.getByText(/Findings are saved frame-level continuity concerns/)).toBeVisible();
  await backgroundPoll;
  await page.keyboard.press('ArrowLeft'); await expect(filmTab).toBeFocused();
  for (const width of [1280, 820, 390]) {
    await page.setViewportSize({ width, height: 900 });
    await filmTab.click();
    await expect(panel.getByRole('list', { name: 'Film Understanding workflow progress' })).toBeVisible();
    await expect(panel.getByText(/Step \d of 5/)).toBeVisible();
    await expect(panel.getByRole('button', { name: 'Refresh now' })).not.toHaveAttribute('data-loading');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: `test-results/pr9-active-${width}.png`, fullPage: true });
  }
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(panel.locator('[data-state=active] .workflow-icon')).toHaveCSS('animation-name', 'none');
  await page.unroute(`**/api/v1/projects/${project.id}/film`);
  await panel.getByRole('button', { name: 'Refresh now' }).click();
  await expect(panel.getByText('Film Understanding complete', { exact: true })).toBeVisible({ timeout: 90000 });
  const saved: FilmIntelligence = await (await request.get(`/api/v1/projects/${project.id}/film`)).json();
  expect(saved.runs[0]!.stage).toBe('SUCCEEDED');
  const writes: string[] = [];
  page.on('request', value => { if (value.method() !== 'GET' && value.url().includes('/api/')) writes.push(value.url()); });
  for (const width of [1280, 820, 390]) {
    await page.setViewportSize({ width, height: 900 });
    await filmTab.click();
    await panel.scrollIntoViewIfNeeded();
    await expect(panel.getByText('Analysis source · 36.29s')).toBeVisible();
    await expect(panel.getByRole('heading', { name: 'Understanding summary' })).toBeVisible();
    await page.screenshot({ path: `test-results/pr9-results-${width}.png`, fullPage: true });
    await panel.getByText('Source details', { exact: true }).click();
    await expect(panel.getByText(/Source replacement is not available/)).toBeVisible();
    await expect(panel.getByText(/Master · 92.46s/)).toBeVisible();
    await page.screenshot({ path: `test-results/pr9-source-${width}.png`, fullPage: true });
    await panel.getByText('Source details', { exact: true }).click();
    const concern = panel.locator('.film-concern').first();
    await concern.scrollIntoViewIfNeeded();
    await concern.screenshot({ path: `test-results/pr9-concern-${width}.png` });
    await concern.getByText(/Inspect supporting evidence/).click();
    await concern.getByRole('button', { name: /Enlarge source frame/ }).first().click();
    const evidence = page.getByRole('dialog');
    await expect(evidence).toHaveCSS('opacity', '1');
    await expect(evidence.getByRole('img', { name: /Full source evidence/ })).toHaveJSProperty('naturalWidth', saved.segments[0]!.shot.frames[0]!.width);
    await page.screenshot({ path: `test-results/pr9-evidence-${width}.png`, animations: 'disabled' });
    await page.keyboard.press('Escape');
    await expect(evidence).toHaveCount(0);
    await concern.getByText(/Inspect supporting evidence/).click();
    await findingsTab.click();
    await expect(page.getByText(/Inspect frame-level continuity issues/)).toBeVisible();
    await page.screenshot({ path: `test-results/pr9-findings-empty-${width}.png`, fullPage: true });
    const help = page.getByText('Why this exists', { exact: true });
    await help.focus(); await page.keyboard.press('Enter');
    await expect(page.getByText(/Planned: Source Monitor/)).toBeVisible();
    await help.locator('..').screenshot({ path: `test-results/pr9-findings-help-${width}.png` });
    await help.click();
    const timeline = page.getByRole('region', { name: 'Keyboard timeline inspection' });
    await timeline.scrollIntoViewIfNeeded(); await timeline.focus();
    const scrollTop = () => timeline.locator('.media-timeline').evaluate(element => element.scrollTop);
    const activeVisible = () => timeline.locator('.media-timeline').evaluate(element => {
      const viewport = element.getBoundingClientRect();
      const frame = element.querySelector('.frame-playhead')!.getBoundingClientRect();
      return frame.top >= viewport.top - 1 && frame.bottom <= viewport.bottom + 1;
    });
    await page.keyboard.press('End');
    await expect.poll(activeVisible).toBe(true);
    await page.keyboard.press('Home');
    await expect.poll(activeVisible).toBe(true);
    const before = await scrollTop();
    await page.getByRole('button', { name: 'Reload saved findings' }).click();
    expect(await scrollTop()).toBe(before);
    await timeline.focus();
    await page.keyboard.press('Home'); await page.keyboard.press('ArrowRight');
    await expect(timeline.getByText('Frame 2 of', { exact: false })).toBeVisible();
    const advanced = timeline.locator('.advanced-inspection');
    if (await advanced.getAttribute('open') !== null) await advanced.getByText('Advanced inspection', { exact: true }).click();
    await timeline.screenshot({ path: `test-results/pr9-advanced-collapsed-${width}.png` });
    await advanced.getByText('Advanced inspection', { exact: true }).focus(); await page.keyboard.press('Space');
    await advanced.getByText('Planned: Analyze Selection', { exact: true }).click();
    await expect(advanced.getByText(/Planned: analyze a selected range/)).toBeVisible();
    await timeline.screenshot({ path: `test-results/pr9-advanced-expanded-${width}.png` });
    await advanced.getByText('Planned: Analyze Selection', { exact: true }).click();
    await timeline.focus();
    await expect(timeline.locator('.inspection-playhead')).toBeVisible();
    await expect.poll(activeVisible).toBe(true);
    await page.screenshot({ path: `test-results/pr9-playhead-${width}.png`, fullPage: true });
    await page.keyboard.press('i'); await page.keyboard.press('Shift+ArrowRight'); await page.keyboard.press('o');
    await expect(timeline.getByTestId('inspection-range')).toBeVisible();
    await expect(timeline.getByRole('button', { name: /Go to Mark In/ })).toBeVisible();
    await expect(timeline.getByRole('button', { name: /Go to Mark Out/ })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: `test-results/pr9-range-${width}.png`, fullPage: true });
    const playhead = await timeline.getByText(/^Playhead/).textContent();
    await filmTab.click(); await findingsTab.click();
    await expect(timeline.getByText(playhead!, { exact: true })).toBeVisible();
    await expect(timeline.getByTestId('inspection-range')).toBeVisible();
    await timeline.focus();
    await page.keyboard.press('Escape');
    await expect(timeline.getByTestId('inspection-range')).toHaveCount(0);
    await page.getByRole('button', { name: 'Delete project', exact: true }).click();
    const confirmation = page.getByRole('dialog', { name: `Delete ${project.name}?` });
    await expect(confirmation).toHaveCSS('opacity', '1');
    await expect(confirmation.getByRole('button', { name: 'Keep project' })).toBeFocused();
    await expect(confirmation.getByRole('button', { name: 'Delete permanently' })).toBeDisabled();
    await page.screenshot({ path: `test-results/pr9-delete-${width}.png`, animations: 'disabled' });
    await confirmation.getByRole('button', { name: 'Keep project' }).click();
  }
  expect(writes).toEqual([]);
  await page.getByRole('button', { name: 'Delete project', exact: true }).click();
  await page.getByLabel('Type the project name to confirm').fill(project.name);
  await page.getByRole('button', { name: 'Delete permanently' }).click();
  await expect(page).toHaveURL('/');
  expect((await request.get(`/api/v1/projects/${project.id}`)).status()).toBe(404);
  expect((await request.get(saved.segments[0]!.shot.frames[0]!.url)).status()).toBe(404);
  expect(writes).toHaveLength(1);
});
