/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/{projectId}/film": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** @description Read source, bounded run history and confirmed anchors. No inference. Private no-store response. */
        get: operations["getFilmIntelligence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/film/source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register one immutable MP4/H.264 primary source. Same content is recoverable; different content requires another project. No provider work. */
        post: operations["uploadSourceFilm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/film/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Explicit paid consent admits one durable Film Understanding attempt. Reuse requestId/source after connection loss. No automatic provider retries. Failed UUID stays failed. Backend stages are authoritative. */
        post: operations["understandFilm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/film/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                runId: string;
            };
            cookie?: never;
        };
        get: operations["getFilmRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/film/runs/{runId}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                runId: string;
            };
            cookie?: never;
        };
        get: operations["getFilmTranscript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/film/runs/{runId}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                runId: string;
            };
            cookie?: never;
        };
        get: operations["getFilmCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/film/candidates/{candidateId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                candidateId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Accept/Edit/Reject without inference. Same decision replays; changed terminal decision conflicts. Only confirmed anchors inform continuity enforcement. */
        post: operations["decideFilmCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/film/candidates/{candidateId}/reference": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                candidateId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Promote the first cited frame of a confirmed anchor through normal ReferenceService. Existing Bible capacity/immutable image rules apply. Same candidate replays. */
        post: operations["promoteFilmCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create or recover the current populated demo copy for a client request UUID. Same UUID always recovers the current copy, including after reset. No model calls. Atomic metadata publication; preparation failures can retry the same UUID. */
        post: operations["openDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Replace only this demo copy with fresh authored data. Retain historical copy and immutable analysis/actions. Ordinary projects return 409. Replays for the same source project recover the current replacement without creating another copy. Does not start inference. */
        post: operations["resetDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** @description Replace trimmed continuity rules, up to 8000 characters. Empty is allowed. No inference; prior analysis snapshots remain unchanged. */
        put: operations["updateProjectRules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/references": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** @description All active visual references, creation time then UUID ascending, at most eight. Archived references remain retrievable by ID and through historical finding evidence. */
        get: operations["listReferences"];
        put?: never;
        /** @description JPEG/PNG only, actual signature and decode, max 10 MiB, 16 MP, 8192 per side. Normalizes PNG to 1600 per side. Image identity is immutable. Max eight active and 100 lifetime references per project. No inference. */
        post: operations["uploadReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/references/{referenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                referenceId: string;
            };
            cookie?: never;
        };
        /** @description Read current metadata, including archived references, within the owning project. */
        get: operations["getReference"];
        /** @description Edit active reference title/guidance. Image cannot change; archived metadata cannot change. Historical analyses retain their submitted metadata. No inference. */
        put: operations["updateReference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/references/{referenceId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                referenceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Idempotent irreversible archive from current Bible. Retains original image and historical usage. Replace an image by archiving then uploading a new reference. No inference. */
        post: operations["archiveReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/references/{referenceId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                referenceId: string;
            };
            cookie?: never;
        };
        /** @description Project-scoped immutable normalized PNG, hash verified, bounded reads; includes archived images. Missing/corrupt content fails safely. */
        get: operations["getReferenceContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/findings/{findingId}/references": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                findingId: string;
            };
            cookie?: never;
        };
        /** @description Only cited references with original submitted title/guidance/dimensions/hash, in submission order. archivedAt reflects current archive state. Zero-reference findings return an empty array. No inference. */
        get: operations["listFindingReferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/findings/{findingId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                findingId: string;
            };
            cookie?: never;
        };
        /** @description Read-only immutable history, oldest first, at most 100 actions. supersedesActionId links the preceding effective judgement; only a successful result becomes effective. Original finding fields/evidence remain intact. */
        get: operations["listFindingActions"];
        put?: never;
        /** @description An explicit INTENTIONAL_CHANGE authorizes one bounded targeted provider call. RESOLVE and DISMISS never call the provider. Scope must exactly match the original affected shots. Replaying the same requestId and payload returns the existing action without inference; changed payload conflicts. Failures retain the action and original finding. A new UUID explicitly authorizes a separate attempt. */
        post: operations["createFindingAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/findings/{findingId}/actions/{actionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                findingId: string;
                actionId: string;
            };
            cookie?: never;
        };
        get: operations["getFindingAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Synchronous, at most one paid call. Reuse requestId after any network retry; an existing RUNNING or final run is returned without another model call. Failed attempts return Problem with analysisRunId. A new requestId explicitly authorizes a new attempt. */
        post: operations["createAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/analyses/{analysisId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/shots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        get: operations["listShots"];
        put?: never;
        post: operations["uploadShot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/frames/{frameId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFrameContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SourceFilm: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            sha256: string;
            byteSize: number;
            durationMs: number;
            /** Format: date-time */
            createdAt: string;
        };
        FilmSegment: {
            /** Format: uuid */
            id: string;
            position: number;
            startMs: number;
            endMs: number;
            shot: components["schemas"]["Shot"];
        };
        TranscriptSegment: {
            /** Format: uuid */
            id: string;
            startMs: number;
            endMs: number;
            text: string;
            timestampOrigin: string;
        };
        FilmEvidence: {
            frameIds: string[];
            transcriptSegmentIds: string[];
        };
        FilmEntity: {
            localId: string;
            name: string;
            description: string;
            evidence: components["schemas"]["FilmEvidence"];
        };
        CandidateAnchor: {
            title: string;
            rule: string;
            scope: string;
            entityIds: string[];
            evidence: components["schemas"]["FilmEvidence"];
            uncertainty: string;
        };
        NarrativeCue: {
            title: string;
            interpretation: string;
            evidence: components["schemas"]["FilmEvidence"];
            uncertainty: string;
        };
        FilmConcern: {
            title: string;
            explanation: string;
            evidence: components["schemas"]["FilmEvidence"];
            uncertainty: string;
        };
        FilmUnderstandingResult: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            sourceFilmId: string;
            schemaVersion: string;
            summary: string;
            inspectedSegmentIds: string[];
            inspectedFrameIds: string[];
            entities: components["schemas"]["FilmEntity"][];
            candidates: components["schemas"]["CandidateAnchor"][];
            narrativeCues: components["schemas"]["NarrativeCue"][];
            potentialConcerns: components["schemas"]["FilmConcern"][];
            warnings: string[];
        };
        FilmRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            sourceFilmId: string;
            /** Format: uuid */
            requestId: string;
            /** @enum {string} */
            stage: "PREPARING_SOURCE" | "DETECTING_STRUCTURE" | "TRANSCRIBING_AUDIO" | "UNDERSTANDING_FILM" | "BUILDING_CANDIDATES" | "SUCCEEDED" | "FAILED";
            /** Format: date-time */
            startedAt: string;
            completedAt: string | null;
            failureCode: string | null;
            failureMessage: string | null;
            stages: {
                /** @enum {string} */
                stage: "PREPARING_SOURCE" | "DETECTING_STRUCTURE" | "TRANSCRIBING_AUDIO" | "UNDERSTANDING_FILM" | "BUILDING_CANDIDATES" | "SUCCEEDED" | "FAILED";
                /** Format: date-time */
                startedAt: string;
                completedAt: string | null;
            }[];
            model: string;
            reasoning: string;
            transcriptionModel: string;
            audioStatus: string | null;
            audioDurationMs: number | null;
            transcriptionRequestId: string | null;
            providerResponseId: string | null;
            providerRequestId: string | null;
            usage: components["schemas"]["AnalysisUsage"] | null;
            result: components["schemas"]["FilmUnderstandingResult"] | null;
        };
        FilmCandidate: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runId: string;
            proposal: components["schemas"]["CandidateAnchor"];
            /** @enum {string} */
            status: "PENDING" | "ACCEPTED" | "EDITED" | "REJECTED";
            confirmedTitle: string | null;
            confirmedRule: string | null;
            confirmedScope: string | null;
            decidedAt: string | null;
            referenceId: string | null;
        };
        ConfirmedFilmAnchor: {
            /** Format: uuid */
            candidateId: string;
            /** Format: uuid */
            sourceFilmId: string;
            /** Format: uuid */
            runId: string;
            title: string;
            rule: string;
            scope: string;
        };
        FilmContextEvidence: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sourceFilmId: string;
            /** Format: uuid */
            runId: string;
            kind: string;
            text: string;
            startMs: number | null;
            endMs: number | null;
            timestampOrigin: string;
            frameIds: string[];
            transcriptSegmentIds: string[];
        };
        FilmIntelligence: {
            source: components["schemas"]["SourceFilm"] | null;
            runs: components["schemas"]["FilmRun"][];
            segments: components["schemas"]["FilmSegment"][];
            confirmedAnchors: components["schemas"]["ConfirmedFilmAnchor"][];
        };
        UnderstandFilmRequest: {
            /** Format: uuid */
            requestId: string;
            /** Format: uuid */
            sourceFilmId: string;
            /** @constant */
            paidConsent: true;
        };
        DecideFilmCandidate: {
            /** @enum {string} */
            status: "ACCEPTED" | "EDITED" | "REJECTED";
            title: string;
            rule: string;
            scope: string;
        };
        UpdateRules: {
            rules: string;
        };
        ReferenceMetadata: {
            title: string;
            guidance: string;
        };
        Reference: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            title: string;
            guidance: string;
            width: number;
            height: number;
            sha256: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            archivedAt: string | null;
            url: string;
            filmProvenance?: null | {
                /** Format: uuid */
                candidateId: string;
                /** Format: uuid */
                runId: string;
                /** Format: uuid */
                sourceFilmId: string;
            };
        };
        CreateFindingAction: {
            /** Format: uuid */
            requestId: string;
            /** @enum {string} */
            type: "INTENTIONAL_CHANGE" | "RESOLVE" | "DISMISS";
            explanation: string;
            scope: string;
            affectedShotIds: string[];
        };
        TargetedResult: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            originalFindingId: string;
            /** @enum {string} */
            schemaVersion: "1";
            /** @enum {string} */
            outcome: "INTENT_ACCEPTED" | "ISSUE_REMAINS" | "INSUFFICIENT_EVIDENCE";
            summary: string;
            explanation: string;
            evaluatedScope: string;
            affectedShotIds: string[];
            evidenceFrameIds: string[];
            inspectedShots: {
                /** Format: uuid */
                shotId: string;
                frameIds: string[];
            }[];
            remainingIssue: string;
            suggestedCorrection: string;
        };
        FindingAction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            findingId: string;
            /** Format: uuid */
            originalAnalysisRunId: string;
            /** Format: uuid */
            requestId: string;
            /** @enum {string} */
            type: "INTENTIONAL_CHANGE" | "RESOLVE" | "DISMISS";
            explanation: string;
            scope: string;
            affectedShotIds: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            supersedesActionId: string | null;
            reanalysis: components["schemas"]["AnalysisRun"] | null;
            result: components["schemas"]["TargetedResult"] | null;
        };
        CreateAnalysis: {
            /** Format: uuid */
            requestId: string;
        };
        AnalysisUsage: {
            inputTokens: number | null;
            outputTokens: number | null;
            totalTokens: number | null;
            cachedInputTokens: number | null;
            reasoningTokens: number | null;
            cacheWriteTokens: number | null;
        };
        AnalysisRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            requestId: string;
            /** @enum {string} */
            status: "RUNNING" | "SUCCEEDED" | "FAILED";
            /** @enum {string} */
            provider: "OPENAI";
            /** @enum {string} */
            model: "gpt-6-astra";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string | null;
            failureCode: string | null;
            failureMessage: string | null;
            shotCount: number;
            frameCount: number;
            projectSummary: string | null;
            warnings: string[];
            usage: components["schemas"]["AnalysisUsage"] | null;
            providerResponseId: string | null;
            providerRequestId: string | null;
            /** @enum {string} */
            kind: "SEQUENCE" | "TARGETED";
        };
        Finding: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            analysisRunId: string;
            /** @enum {string} */
            category: "CHARACTER_IDENTITY" | "CHARACTER_APPEARANCE" | "HAIR" | "WARDROBE" | "PROP" | "OBJECT_STATE" | "ENVIRONMENT" | "SPATIAL_CONTINUITY" | "SCREEN_DIRECTION" | "LIGHTING" | "TIME_OF_DAY" | "HAND_OBJECT_INTERACTION" | "DEVICE_UI" | "TEXT_CONTINUITY" | "OTHER";
            /** @enum {string} */
            severity: "LOW" | "MEDIUM" | "HIGH";
            confidence: number;
            title: string;
            summary: string;
            expectedState: string;
            observedState: string;
            explanation: string;
            affectedShotIds: string[];
            relevantFrameIds: string[];
            relevantReferenceIds: string[];
            filmEvidence?: components["schemas"]["FilmContextEvidence"][];
            suggestedCorrectionPrompt: string;
            /** @enum {string} */
            status: "OPEN" | "RESOLVED" | "INTENTIONAL" | "DISMISSED";
        };
        Frame: {
            /** Format: uuid */
            id: string;
            position: number;
            timestampMs: number | null;
            width: number;
            height: number;
            url: string;
        };
        Shot: {
            /** Format: uuid */
            id: string;
            position: number;
            name: string;
            /** @enum {string} */
            kind: "IMAGE" | "VIDEO" | "UNKNOWN";
            /** @enum {string} */
            status: "READY" | "FAILED";
            failureCode: string | null;
            durationMs: number | null;
            frames: components["schemas"]["Frame"][];
        };
        CreateProject: {
            name: string;
            /** @default  */
            description: string;
            /** @default  */
            rules: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            rules: string;
            /** Format: date-time */
            createdAt: string;
            demo?: {
                /** Format: uuid */
                instanceId: string;
                templateVersion: string;
                retired: boolean;
            } | null;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            page: number;
            hasNext: boolean;
        };
        Problem: {
            /**
             * Format: uri
             * @description Omission means about:blank per RFC 9457.
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /**
             * Format: uuid
             * @description Durable run identifier when an admitted analysis fails.
             */
            analysisRunId?: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem response */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getFilmIntelligence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmIntelligence"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    uploadSourceFilm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Persisted result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFilm"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    understandFilm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnderstandFilmRequest"];
            };
        };
        responses: {
            /** @description Persisted result */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getFilmRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getFilmTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptSegment"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getFilmCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmCandidate"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    decideFilmCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideFilmCandidate"];
            };
        };
        responses: {
            /** @description Persisted result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmCandidate"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    promoteFilmCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmCandidate"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    openDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    requestId: string;
                };
            };
        };
        responses: {
            /** @description Ready working demo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    resetDemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready replacement demo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateProjectRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRules"];
            };
        };
        responses: {
            /** @description Saved project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listReferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active Bible */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reference"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    uploadReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    title: string;
                    guidance: string;
                };
            };
        };
        responses: {
            /** @description Persisted normalized reference */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reference"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                referenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reference */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reference"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                referenceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceMetadata"];
            };
        };
        responses: {
            /** @description Saved reference */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reference"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    archiveReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                referenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived reference */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reference"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReferenceContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                referenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized PNG */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listFindingReferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                findingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historical reference evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reference"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listFindingActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                findingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable creator action and actual targeted result, if available */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingAction"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createFindingAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                findingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFindingAction"];
            };
        };
        responses: {
            /** @description Durable creator action and actual targeted result, if available */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingAction"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getFindingAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                findingId: string;
                actionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable creator action and actual targeted result, if available */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingAction"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysis"];
            };
        };
        responses: {
            /** @description Current durable run; Location identifies its GET endpoint */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                analysisId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable analysis state; stale interrupted runs become FAILED after five minutes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listFindings: {
        parameters: {
            query?: {
                analysisId?: string;
                page?: number;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validated findings, newest analysis first, at most 20 per page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listShots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 100 import attempts in durable order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shot"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    uploadShot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Imported shot with normalized frames */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shot"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getFrameContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                frameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized frame; project membership checked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects, newest first; pages contain at most 20 items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Project persisted */
            201: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
